name: 'RelizaHub Build And Submit Release metadata action'
description: 'RelizaHub Build And Submit Release metadata action'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  registry_host:
    description: "Host for image registry"
    default: null
    required: false
  image_namespace:
    description: "Namespace of the image on registry"
    required: true
  image_name:
    description: "Name of the image"
    required: true
  reliza_api_id:
    description: "Reliza Hub API ID"
    required: true
  reliza_api_key:
    description: "Reliza Hub API KEY"
    required: true
  reliza_api_url:
    description: "Reliza Hub API URL"
    required: false
    default: 'https://app.relizahub.com'
  path:
    description: "Path to the relative to root of the repo (default is '.')"
    required: false
    default: .
  dockerfile_name:
    description: "Name of the dockerfile (default is 'Dockerfile')"
    required: false
    default: Dockerfile
  ci_metadata:
    description: "Metadata for CI run, (Optional - default is GitHub)"
    required: false
runs:
  using: "composite"
  steps:
    - id: setup-reliza-cli
      name: setup-reliza-cli
      uses: relizaio/setup-reliza-cli@1.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      if: ${{ inputs.registry_host == null }}
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - name: Login to Docker Registry
      uses: docker/login-action@v2.1.0
      if: ${{ inputs.registry_host != null }}
      with:
        registry: ${{inputs.registry_host}}
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - id: get-version
      name: Get Version
      uses: relizaio/reliza-get-version@1.0
      with: 
        reliza_api_id: ${{ inputs.reliza_api_id }}
        reliza_api_key: ${{ inputs.reliza_api_key }}
        reliza_api_url: ${{inputs.reliza_api_url}}
        path: ${{inputs.path}}
        ci_metadata: "${{inputs.ci_metadata}}"
    - name: Instantiate Reliza status as Rejected to handle possible build failure
      shell: bash
      run: |
        echo "RELIZA_BUILD_STATUS=rejected" >> $GITHUB_ENV
        echo "RELIZA_DO_BUILD=${{ steps.get-version.outputs.reliza_do_build}}" >> $GITHUB_ENV
    - name: Build and push docker container to Reliza Hub Registry
      shell: bash
      if: ${{env.RELIZA_DO_BUILD == 'true'}}
      continue-on-error: true
      run: |
        cd ${{ inputs.path }}
        
        branch_name=${{github.ref_name}}
        case $branch_name in

          master | main)
            latest_tag=latest
            ;;

          *)
            latest_tag=$branch_name
            ;;
        esac

        docker build \
          -t ${{inputs.image_namespace}}/${{inputs.image_name}}:${{ steps.get-version.outputs.reliza_short_version }} \
          -t ${{inputs.image_namespace}}/${{inputs.image_name}}:$latest_tag \
          --build-arg VERSION=${{ steps.get-version.outputs.reliza_full_version }} \
          --build-arg CI_ENV=github${{github.sha}} \
          --build-arg GIT_COMMIT=${{github.sha}} \
          --build-arg GIT_BRANCH=${{github.ref_name}} \
          -f ${{inputs.dockerfile_name}} .
        docker_sha_256=$(docker push ${{inputs.image_namespace}}/${{inputs.image_name}}:${{ steps.get-version.outputs.reliza_short_version }} | grep sha256 | cut -f 3 -d ' ')
        # push latest_tag also
        docker push ${{inputs.image_namespace}}/${{inputs.image_name}}:$latest_tag
        # save sha256 to env var
        echo "DOCKER_SHA_256=$docker_sha_256" >> $GITHUB_ENV
        echo "RELIZA_BUILD_STATUS=complete " >> $GITHUB_ENV
    - name: Submit metadata to Reliza Hub
      uses: relizaio/reliza-add-release@1.0
      if: ${{env.RELIZA_DO_BUILD == 'true'}}
      with:
        reliza_api_id: ${{ inputs.reliza_api_id }}
        reliza_api_key: ${{ inputs.reliza_api_key }}
        reliza_api_url: ${{inputs.reliza_api_url}}
        image_full_name: ${{inputs.image_namespace}}/${{inputs.image_name}}
        image_digest: $DOCKER_SHA_256
        reliza_full_version: ${{ steps.get-version.outputs.reliza_full_version }}
        reliza_build_start: ${{ steps.get-version.outputs.reliza_build_start }}
        reliza_build_status: $RELIZA_BUILD_STATUS
